sonar.projectKey=evidence-demo-app
sonar.projectName=Evidence Demo App
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=app
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-results/junit.xml
